#!/usr/bin/env python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSController
from mininet.node import CPULimitedHost, Host, Node
from mininet.node import OVSKernelSwitch, UserSwitch
from mininet.node import IVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink, Intf
from subprocess import call

def myNetwork():

    net = Mininet( topo=None,
                   listenPort=6633,
                   build=False,
                   ipBase='10.0.0.0/8')

    info( '*** Adding controller\n' )
    c0=net.addController(name='c0',
                      controller=RemoteController,
                      ip='127.0.0.1',
                      protocol='tcp',
                      port=6633)

    info( '*** Add switches\n')
    s71 = net.addSwitch('s71', cls=OVSKernelSwitch, failMode='standalone')
    s52 = net.addSwitch('s52', cls=OVSKernelSwitch, failMode='standalone')
    s18 = net.addSwitch('s18', cls=OVSKernelSwitch)
    s3 = net.addSwitch('s3', cls=OVSKernelSwitch, failMode='standalone')
    s9 = net.addSwitch('s9', cls=OVSKernelSwitch)
    s49 = net.addSwitch('s49', cls=OVSKernelSwitch)
    s36 = net.addSwitch('s36', cls=OVSKernelSwitch)
    s35 = net.addSwitch('s35', cls=OVSKernelSwitch)
    s34 = net.addSwitch('s34', cls=OVSKernelSwitch)
    s27 = net.addSwitch('s27', cls=OVSKernelSwitch, failMode='standalone')
    s64 = net.addSwitch('s64', cls=OVSKernelSwitch)
    s23 = net.addSwitch('s23', cls=OVSKernelSwitch)
    s58 = net.addSwitch('s58', cls=OVSKernelSwitch, failMode='standalone')
    s42 = net.addSwitch('s42', cls=OVSKernelSwitch)
    s59 = net.addSwitch('s59', cls=OVSKernelSwitch, failMode='standalone')
    s21 = net.addSwitch('s21', cls=OVSKernelSwitch)
    s63 = net.addSwitch('s63', cls=OVSKernelSwitch)
    s32 = net.addSwitch('s32', cls=OVSKernelSwitch)
    s69 = net.addSwitch('s69', cls=OVSKernelSwitch, failMode='standalone')
    s68 = net.addSwitch('s68', cls=OVSKernelSwitch, failMode='standalone')
    s56 = net.addSwitch('s56', cls=OVSKernelSwitch, failMode='standalone')
    s65 = net.addSwitch('s65', cls=OVSKernelSwitch)
    s2 = net.addSwitch('s2', cls=OVSKernelSwitch, failMode='standalone')
    s53 = net.addSwitch('s53', cls=OVSKernelSwitch, failMode='standalone')
    s30 = net.addSwitch('s30', cls=OVSKernelSwitch)
    s31 = net.addSwitch('s31', cls=OVSKernelSwitch)
    s10 = net.addSwitch('s10', cls=OVSKernelSwitch)
    s29 = net.addSwitch('s29', cls=OVSKernelSwitch)
    s7 = net.addSwitch('s7', cls=OVSKernelSwitch, failMode='standalone')
    s1 = net.addSwitch('s1', cls=OVSKernelSwitch, failMode='standalone')
    s22 = net.addSwitch('s22', cls=OVSKernelSwitch)
    s70 = net.addSwitch('s70', cls=OVSKernelSwitch, failMode='standalone')
    s50 = net.addSwitch('s50', cls=OVSKernelSwitch, failMode='standalone')
    s44 = net.addSwitch('s44', cls=OVSKernelSwitch)
    s11 = net.addSwitch('s11', cls=OVSKernelSwitch)
    s5 = net.addSwitch('s5', cls=OVSKernelSwitch, failMode='standalone')
    s66 = net.addSwitch('s66', cls=OVSKernelSwitch)
    s25 = net.addSwitch('s25', cls=OVSKernelSwitch)
    s61 = net.addSwitch('s61', cls=OVSKernelSwitch)
    s67 = net.addSwitch('s67', cls=OVSKernelSwitch)
    s6 = net.addSwitch('s6', cls=OVSKernelSwitch, failMode='standalone')
    s33 = net.addSwitch('s33', cls=OVSKernelSwitch)
    s41 = net.addSwitch('s41', cls=OVSKernelSwitch)
    s12 = net.addSwitch('s12', cls=OVSKernelSwitch)
    s24 = net.addSwitch('s24', cls=OVSKernelSwitch)
    s17 = net.addSwitch('s17', cls=OVSKernelSwitch)
    s62 = net.addSwitch('s62', cls=OVSKernelSwitch)
    s47 = net.addSwitch('s47', cls=OVSKernelSwitch)
    s46 = net.addSwitch('s46', cls=OVSKernelSwitch)
    s45 = net.addSwitch('s45', cls=OVSKernelSwitch)
    s55 = net.addSwitch('s55', cls=OVSKernelSwitch, failMode='standalone')
    s8 = net.addSwitch('s8', cls=OVSKernelSwitch)
    s37 = net.addSwitch('s37', cls=OVSKernelSwitch)
    s4 = net.addSwitch('s4', cls=OVSKernelSwitch, failMode='standalone')
    s13 = net.addSwitch('s13', cls=OVSKernelSwitch)
    s39 = net.addSwitch('s39', cls=OVSKernelSwitch)
    s28 = net.addSwitch('s28', cls=OVSKernelSwitch, failMode='standalone')
    s51 = net.addSwitch('s51', cls=OVSKernelSwitch, failMode='standalone')
    s19 = net.addSwitch('s19', cls=OVSKernelSwitch)
    s15 = net.addSwitch('s15', cls=OVSKernelSwitch)
    s14 = net.addSwitch('s14', cls=OVSKernelSwitch)
    s40 = net.addSwitch('s40', cls=OVSKernelSwitch)
    s16 = net.addSwitch('s16', cls=OVSKernelSwitch)
    s43 = net.addSwitch('s43', cls=OVSKernelSwitch)
    s20 = net.addSwitch('s20', cls=OVSKernelSwitch)
    s38 = net.addSwitch('s38', cls=OVSKernelSwitch)
    s48 = net.addSwitch('s48', cls=OVSKernelSwitch)
    s26 = net.addSwitch('s26', cls=OVSKernelSwitch, failMode='standalone')
    s60 = net.addSwitch('s60', cls=OVSKernelSwitch, failMode='standalone')
    s54 = net.addSwitch('s54', cls=OVSKernelSwitch, failMode='standalone')

    info( '*** Add hosts\n')
    h30 = net.addHost('h30', cls=Host, ip='10.0.0.30', defaultRoute=None)
    h19 = net.addHost('h19', cls=Host, ip='10.0.0.19', defaultRoute=None)
    h10 = net.addHost('h10', cls=Host, ip='10.0.0.10', defaultRoute=None)
    h31 = net.addHost('h31', cls=Host, ip='10.0.0.31', defaultRoute=None)
    h8 = net.addHost('h8', cls=Host, ip='10.0.0.8', defaultRoute=None)
    h12 = net.addHost('h12', cls=Host, ip='10.0.0.12', defaultRoute=None)
    h22 = net.addHost('h22', cls=Host, ip='10.0.0.22', defaultRoute=None)
    h4 = net.addHost('h4', cls=Host, ip='10.0.0.4', defaultRoute=None)
    h27 = net.addHost('h27', cls=Host, ip='10.0.0.27', defaultRoute=None)
    h25 = net.addHost('h25', cls=Host, ip='10.0.0.25', defaultRoute=None)
    h5 = net.addHost('h5', cls=Host, ip='10.0.0.5', defaultRoute=None)
    h34 = net.addHost('h34', cls=Host, ip='10.0.0.34', defaultRoute=None)
    h16 = net.addHost('h16', cls=Host, ip='10.0.0.16', defaultRoute=None)
    h29 = net.addHost('h29', cls=Host, ip='10.0.0.29', defaultRoute=None)
    h32 = net.addHost('h32', cls=Host, ip='10.0.0.32', defaultRoute=None)
    h11 = net.addHost('h11', cls=Host, ip='10.0.0.11', defaultRoute=None)
    h15 = net.addHost('h15', cls=Host, ip='10.0.0.15', defaultRoute=None)
    h1 = net.addHost('h1', cls=Host, ip='10.0.0.1', defaultRoute=None)
    h2 = net.addHost('h2', cls=Host, ip='10.0.0.2', defaultRoute=None)
    h21 = net.addHost('h21', cls=Host, ip='10.0.0.21', defaultRoute=None)
    h3 = net.addHost('h3', cls=Host, ip='10.0.0.3', defaultRoute=None)
    h38 = net.addHost('h38', cls=Host, ip='10.0.0.38', defaultRoute=None)
    h13 = net.addHost('h13', cls=Host, ip='10.0.0.13', defaultRoute=None)
    h6 = net.addHost('h6', cls=Host, ip='10.0.0.6', defaultRoute=None)
    h28 = net.addHost('h28', cls=Host, ip='10.0.0.28', defaultRoute=None)
    h36 = net.addHost('h36', cls=Host, ip='10.0.0.36', defaultRoute=None)
    h26 = net.addHost('h26', cls=Host, ip='10.0.0.26', defaultRoute=None)
    h17 = net.addHost('h17', cls=Host, ip='10.0.0.17', defaultRoute=None)
    h24 = net.addHost('h24', cls=Host, ip='10.0.0.24', defaultRoute=None)
    h33 = net.addHost('h33', cls=Host, ip='10.0.0.33', defaultRoute=None)
    h37 = net.addHost('h37', cls=Host, ip='10.0.0.37', defaultRoute=None)
    h35 = net.addHost('h35', cls=Host, ip='10.0.0.35', defaultRoute=None)
    h14 = net.addHost('h14', cls=Host, ip='10.0.0.14', defaultRoute=None)
    h20 = net.addHost('h20', cls=Host, ip='10.0.0.20', defaultRoute=None)
    h7 = net.addHost('h7', cls=Host, ip='10.0.0.7', defaultRoute=None)
    h9 = net.addHost('h9', cls=Host, ip='10.0.0.9', defaultRoute=None)
    h18 = net.addHost('h18', cls=Host, ip='10.0.0.18', defaultRoute=None)

    info( '*** Add links\n')
    net.addLink(h1, s1)
    net.addLink(h2, s2)
    net.addLink(h3, s3)
    net.addLink(h6, s5)
    net.addLink(h5, s4)
    net.addLink(s4, h4)
    net.addLink(s6, h7)
    net.addLink(s6, h8)
    net.addLink(s7, h9)
    net.addLink(s11, s12)
    net.addLink(s12, s14)
    net.addLink(s14, s15)
    net.addLink(s13, s15)
    net.addLink(s13, s11)
    net.addLink(s11, s8)
    net.addLink(s12, s9)
    net.addLink(s9, s4)
    net.addLink(s9, s5)
    net.addLink(s13, s10)
    net.addLink(s10, s6)
    net.addLink(s10, s7)
    net.addLink(s1, s8)
    net.addLink(s2, s8)
    net.addLink(s8, s3)
    net.addLink(s18, s19)
    net.addLink(s18, s16)
    net.addLink(s19, s20)
    net.addLink(s20, s17)
    net.addLink(s16, s17)
    net.addLink(s21, s19)
    net.addLink(s20, s22)
    net.addLink(s22, s26)
    net.addLink(s22, s27)
    net.addLink(s22, s28)
    net.addLink(s26, h13)
    net.addLink(s27, h14)
    net.addLink(s28, h15)
    net.addLink(s14, s29)
    net.addLink(s15, s30)
    net.addLink(s30, s29)
    net.addLink(s14, s30)
    net.addLink(s29, s15)
    net.addLink(s29, s16)
    net.addLink(s31, s17)
    net.addLink(s17, s29)
    net.addLink(s16, s31)
    net.addLink(s29, s31)
    net.addLink(s31, s32)
    net.addLink(s32, s34)
    net.addLink(s31, s33)
    net.addLink(s32, s33)
    net.addLink(s31, s34)
    net.addLink(s29, s33)
    net.addLink(s34, s35)
    net.addLink(s35, s37)
    net.addLink(s35, s36)
    net.addLink(s35, s38)
    net.addLink(s38, s36)
    net.addLink(s37, s36)
    net.addLink(s34, s38)
    net.addLink(s35, s33)
    net.addLink(s30, s31)
    net.addLink(s60, h28)
    net.addLink(s60, h29)
    net.addLink(s59, h26)
    net.addLink(s59, h27)
    net.addLink(s58, h25)
    net.addLink(s58, h24)
    net.addLink(s61, s35)
    net.addLink(s62, s37)
    net.addLink(s61, s62)
    net.addLink(s62, s35)
    net.addLink(s61, s37)
    net.addLink(s61, s63)
    net.addLink(s63, s64)
    net.addLink(s64, s65)
    net.addLink(s65, s62)
    net.addLink(s64, s66)
    net.addLink(s65, s67)
    net.addLink(s66, s68)
    net.addLink(s66, s69)
    net.addLink(s67, s70)
    net.addLink(s67, s71)
    net.addLink(s68, h30)
    net.addLink(s69, h31)
    net.addLink(s70, h32)
    net.addLink(s71, h33)
    net.addLink(s36, s40)
    net.addLink(s40, s44)
    net.addLink(s38, s44)
    net.addLink(s36, s44)
    net.addLink(s38, s40)
    net.addLink(s40, s41)
    net.addLink(s41, s42)
    net.addLink(s42, s43)
    net.addLink(s43, s44)
    net.addLink(s43, s46)
    net.addLink(s46, s58)
    net.addLink(s46, s59)
    net.addLink(s42, s45)
    net.addLink(s45, s60)
    net.addLink(s32, s47)
    net.addLink(s33, s24)
    net.addLink(s32, s24)
    net.addLink(s33, s47)
    net.addLink(s47, s48)
    net.addLink(s47, s24)
    net.addLink(s24, s23)
    net.addLink(s48, s49)
    net.addLink(s49, s23)
    net.addLink(s49, s39)
    net.addLink(s25, s48)
    net.addLink(s25, s53)
    net.addLink(s25, s54)
    net.addLink(s53, h17)
    net.addLink(h19, s54)
    net.addLink(s54, h18)
    net.addLink(s55, h21)
    net.addLink(s55, h20)
    net.addLink(s56, h22)
    net.addLink(s39, s56)
    net.addLink(s39, s55)
    net.addLink(h16, s53)
    net.addLink(s21, s50)
    net.addLink(s50, h10)
    net.addLink(s21, s51)
    net.addLink(s51, h11)
    net.addLink(s21, s52)
    net.addLink(s52, h12)
    net.addLink(h34, s30)
    net.addLink(h35, s32)
    net.addLink(s34, h36)
    net.addLink(h37, s36)
    net.addLink(s37, h38)

    info( '*** Starting network\n')
    net.build()
    info( '*** Starting controllers\n')
    for controller in net.controllers:
        controller.start()

    info( '*** Starting switches\n')
    net.get('s71').start([])
    net.get('s52').start([])
    net.get('s18').start([c0])
    net.get('s3').start([])
    net.get('s9').start([c0])
    net.get('s49').start([c0])
    net.get('s36').start([c0])
    net.get('s35').start([c0])
    net.get('s34').start([c0])
    net.get('s27').start([])
    net.get('s64').start([c0])
    net.get('s23').start([])
    net.get('s58').start([])
    net.get('s42').start([c0])
    net.get('s59').start([])
    net.get('s21').start([c0])
    net.get('s63').start([c0])
    net.get('s32').start([c0])
    net.get('s69').start([])
    net.get('s68').start([])
    net.get('s56').start([])
    net.get('s65').start([c0])
    net.get('s2').start([])
    net.get('s53').start([])
    net.get('s30').start([c0])
    net.get('s31').start([c0])
    net.get('s10').start([c0])
    net.get('s29').start([c0])
    net.get('s7').start([])
    net.get('s1').start([])
    net.get('s22').start([c0])
    net.get('s70').start([])
    net.get('s50').start([])
    net.get('s44').start([c0])
    net.get('s11').start([c0])
    net.get('s5').start([])
    net.get('s66').start([c0])
    net.get('s25').start([c0])
    net.get('s61').start([c0])
    net.get('s67').start([c0])
    net.get('s6').start([])
    net.get('s33').start([c0])
    net.get('s41').start([c0])
    net.get('s12').start([c0])
    net.get('s24').start([])
    net.get('s17').start([c0])
    net.get('s62').start([c0])
    net.get('s47').start([c0])
    net.get('s46').start([c0])
    net.get('s45').start([c0])
    net.get('s55').start([])
    net.get('s8').start([c0])
    net.get('s37').start([c0])
    net.get('s4').start([])
    net.get('s13').start([c0])
    net.get('s39').start([c0])
    net.get('s28').start([])
    net.get('s51').start([])
    net.get('s19').start([c0])
    net.get('s15').start([c0])
    net.get('s14').start([c0])
    net.get('s40').start([c0])
    net.get('s16').start([c0])
    net.get('s43').start([c0])
    net.get('s20').start([c0])
    net.get('s38').start([c0])
    net.get('s48').start([c0])
    net.get('s26').start([])
    net.get('s60').start([])
    net.get('s54').start([])

    info( '*** Post configure switches and hosts\n')

    CLI(net)
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    myNetwork()

